const data = [
  {
    firstName: "Pranav ",
    lastName: "Jayachandran",
    id: "0",
    bloodGroup: "O+",
    sugarLevel: 1,
    bloodPressure: 2,
    RBCCount: 3,
    WBCCount: 4,
    Haemoglobin: 5,
    Height: 6,
    Weight: 7,
    Owner: 8,
  },
  {
    firstName: "Pranav ",
    lastName: "Jayachandran",
    id: "0",
    bloodGroup: "O+",
    sugarLevel: 1,
    bloodPressure: 2,
    RBCCount: 3,
    WBCCount: 4,
    Haemoglobin: 5,
    Height: 6,
    Weight: 7,
    Owner: 8,
  },
  {
    firstName: "Pranav ",
    lastName: "Jayachandran",
    id: "0",
    bloodGroup: "O+",
    sugarLevel: 1,
    bloodPressure: 2,
    RBCCount: 3,
    WBCCount: 4,
    Haemoglobin: 5,
    Height: 6,
    Weight: 7,
    Owner: 8,
  },

  {
    firstName: "Pranav ",
    lastName: "Jayachandran",
    id: "0",
    bloodGroup: "O+",
    sugarLevel: 1,
    bloodPressure: 2,
    RBCCount: 3,
    WBCCount: 4,
    Haemoglobin: 5,
    Height: 6,
    Weight: 7,
    Owner: 8,
  },
  {
    firstName: "Pranav ",
    lastName: "Jayachandran",
    id: "0",
    bloodGroup: "O+",
    sugarLevel: 1,
    bloodPressure: 2,
    RBCCount: 3,
    WBCCount: 4,
    Haemoglobin: 5,
    Height: 6,
    Weight: 7,
    Owner: 8,
  },
  {
    firstName: "Pranav ",
    lastName: "Jayachandran",
    id: "0",
    bloodGroup: "O+",
    sugarLevel: 1,
    bloodPressure: 2,
    RBCCount: 3,
    WBCCount: 4,
    Haemoglobin: 5,
    Height: 6,
    Weight: 7,
    Owner: 8,
  },
  {
    firstName: "Pranav ",
    lastName: "Jayachandran",
    id: "0",
    bloodGroup: "O+",
    sugarLevel: 1,
    bloodPressure: 2,
    RBCCount: 3,
    WBCCount: 4,
    Haemoglobin: 5,
    Height: 6,
    Weight: 7,
    Owner: 8,
  },
];

export default data;
